### ISSUE TITLE
VIP Dataset on Google Drive

### ISSUE THREAD

**Issue by sberryman** [HCPLab-SYSU/ATEN#1]
Any chance you can upload the VIP dataset to Google Drive? I'm unable to download it from Baidu drive here in the states.

Thanks!

**Comment by zhouqixian** [comment]
The VIP dataset and ATEN models will be uploaded on Dropbox in a few days.

**Comment by HCPLab-SYSU** [comment]
VIP dataset is available now! 
The OneDrive link: https://1drv.ms/f/s!ArFSFaZzVErwgSHRpiJNJTzgMR8j

**Comment by sberryman** [comment]
Confirmed! Looking forward to running some tests, thank you!

**Comment by VyBui** [comment]
@sberryman would you guys please share the models. I could not find it in Baidu either OneDrive.

**Comment by sberryman** [comment]
Sorry @VyBui I don't have the data any longer.

**Comment by zhouqixian** [comment]
@VyBui The OneDrive link is unavailable now and I will uploaded it again. You can download the [dataset](https://pan.baidu.com/s/18_PVNy7FCh4T74nVzRXbtA#list/path=%2FVIP&parentPath=%2F) and [model](https://pan.baidu.com/s/1tZfm3Prvzn47cZi5RZ-lNw) from Baidu where the link is available.
