### ISSUE TITLE
Could you please release the evaluation code for the vip dataset?

### ISSUE THREAD

**Issue by vana77** [HCPLab-SYSU/ATEN#3]
I could only find the visualization code. But there is no evaluation metric code released, i.e., the reported mIOU and AP scores.

**Comment by zhouqixian** [comment]
Evaluation code and evaluation platform for test set are coming soon. I will upload the evaluation code in a few day.

**Comment by vana77** [comment]
Thanks for your quick reply. But I am not sure whether the parsing results on the adjacent frames are calculated in the mIOU score. It seems that there is no groundtruth for these frames.

**Comment by zhouqixian** [comment]
As we only densely annotate the video frames every 25 frame, there are not groundtruth for adjacent frames. We just evaluate the parsing results on annotated frame.
