### ISSUE TITLE
VIP dataset lost some frames in every video

### ISSUE THREAD

**Issue by JasonDu1993** [HCPLab-SYSU/ATEN#5]
I downloaded the VIP, but I found every video lost some frames, such as the thirteenth frame. How I can get the complete frames or videos

**Comment by zhouqixian** [comment]
I have uploaded the complete videos on [OneDrive](https://onedrive.live.com/?authkey=%21ANGmIk0lPOAxHyM&id=F04A5473A61552B1%21161&cid=F04A5473A61552B1). You can directly download the source videos and extract any frames you need. One thing to note is that the index number of the video frames is labeled from 1 to n (not from 0 to n). The "000000000001.jpg" is the first frame of video.

**Comment by JasonDu1993** [comment]
> I have uploaded the complete videos on [OneDrive](https://onedrive.live.com/?authkey=%21ANGmIk0lPOAxHyM&id=F04A5473A61552B1%21161&cid=F04A5473A61552B1). You can directly download the source videos and extract any frames you need. One thing to note is that the index number of the video frames is labeled from 1 to n (not from 0 to n). The "000000000001.jpg" is the first frame of video.
Can provide baidu cloud link，thanks

**Comment by zhouqixian** [comment]
https://1drv.ms/f/s!ArFSFaZzVErwgTjHQvDWAQJhCoe7

**Comment by zhouqixian** [comment]
Oh, I only uploaded it on OneDrive. I can upload it on Baidu Cloud now but you need to wait for several hour.

**Comment by JasonDu1993** [comment]
> Oh, I only uploaded it on OneDrive. I can upload it on Baidu Cloud now but you need to wait for several hour.

OK, thanks!

**Comment by JasonDu1993** [comment]
LIP dataset official website can't register by QQ mail?

**Comment by JasonDu1993** [comment]
How can I contact you by e-mail?
