### ISSUE TITLE
module 'keras.layers' has no attribute 'ConvGRU2D'

### ISSUE THREAD

**Issue by qchenclaire** [HCPLab-SYSU/ATEN#6]
Hi I've already install the requirements as specified in Readme.md and the compilation was sucessful. But I got the error when I was trying to run the program by `python scripts/vip/train_aten.py`
`/data/APL/ATEN/aten_model.py(676)conv_gru_unit()
x = KL.ConvGRU2D(filters=256, kernel_size=(3, 3), name="gru_recurrent_unit",
AttributeError: module 'keras.layers' has no attribute 'ConvGRU2D'
`
The output of dir(keras.layers) is:
`['Activation', 'ActivityRegularization', 'Add', 'AlphaDropout', 'AtrousConv1D', 'AtrousConv2D', 'AtrousConvolution1D', 'AtrousConvolution2D', 'Average', 'AveragePooling1D', 'AveragePooling2D', 'AveragePooling3D', 'AvgPool1D', 'AvgPool2D', 'AvgPool3D', 'BatchNormalization', 'Bidirectional', 'Concatenate', 'Conv1D', 'Conv2D', 'Conv2DTranspose', 'Conv3D', 'Conv3DTranspose', 'ConvLSTM2D', 'ConvLSTM2DCell', 'ConvRNN2D', 'ConvRecurrent2D', 'Convolution1D', 'Convolution2D', 'Convolution2DTranspose', 'Convolution3D', 'Cropping1D', 'Cropping2D', 'Cropping3D', 'CuDNNGRU', 'CuDNNLSTM', 'Deconv2D', 'Deconv3D', 'Deconvolution2D', 'Deconvolution3D', 'Dense', 'DepthwiseConv2D', 'Dot', 'Dropout', 'ELU', 'Embedding', 'Flatten', 'GRU', 'GRUCell', 'GaussianDropout', 'GaussianNoise', 'GlobalAveragePooling1D', 'GlobalAveragePooling2D', 'GlobalAveragePooling3D', 'GlobalAvgPool1D', 'GlobalAvgPool2D', 'GlobalAvgPool3D', 'GlobalMaxPool1D', 'GlobalMaxPool2D', 'GlobalMaxPool3D', 'GlobalMaxPooling1D', 'GlobalMaxPooling2D', 'GlobalMaxPooling3D', 'Highway', 'Input', 'InputLayer', 'InputSpec', 'K', 'LSTM', 'LSTMCell', 'Lambda', 'Layer', 'LeakyReLU', 'LocallyConnected1D', 'LocallyConnected2D', 'Masking', 'MaxPool1D', 'MaxPool2D', 'MaxPool3D', 'MaxPooling1D', 'MaxPooling2D', 'MaxPooling3D', 'Maximum', 'MaxoutDense', 'Minimum', 'Multiply', 'PReLU', 'Permute', 'RNN', 'ReLU', 'Recurrent', 'RepeatVector', 'Reshape', 'SeparableConv1D', 'SeparableConv2D', 'SeparableConvolution1D', 'SeparableConvolution2D', 'SimpleRNN', 'SimpleRNNCell', 'Softmax', 'SpatialDropout1D', 'SpatialDropout2D', 'SpatialDropout3D', 'StackedRNNCells', 'Subtract', 'ThresholdedReLU', 'TimeDistributed', 'UpSampling1D', 'UpSampling2D', 'UpSampling3D', 'Wrapper', 'ZeroPadding1D', 'ZeroPadding2D', 'ZeroPadding3D', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'activations', 'add', 'advanced_activations', 'average', 'concatenate', 'constraints', 'conv_utils', 'convolutional', 'convolutional_recurrent', 'copy', 'core', 'cudnn_recurrent', 'deserialize', 'deserialize_keras_object', 'division', 'dot', 'embeddings', 'func_dump', 'func_load', 'has_arg', 'initializers', 'interfaces', 'local', 'maximum', 'merge', 'minimum', 'multiply', 'namedtuple', 'noise', 'normalization', 'np', 'object_list_uid', 'pooling', 'print_function', 'python_types', 'recurrent', 'regularizers', 'serialize', 'subtract', 'to_list', 'transpose_shape', 'warnings', 'wrappers']
`
I'm using docker tf 1.10

**Comment by zhouqixian** [comment]
@qchenclaire Please install keras_convGRU provided by this repo (a specific keras version which implement the convGRU layer)

**Comment by JonathanLehner** [comment]
i also get this error

 InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FlowWarp' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: lambda_56/FlowWarp_1 = FlowWarp[](lambda_56/Placeholder, lambda_56/Placeholder_1)]]
